default: &default
  adapter: postgresql
  encoding: unicode
  pool: 8

development:
  <<: *default
  database: mutabaah_development
  username: postgres
  password: 123456

test:
  <<: *default
  database: mutabaah_test
  username: postgres
  password: 123456

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
