# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e5cdfa90cdc63a71dd84728c3c890f9346371c1a396fc952ee446df770882f09287654ca7a903912a9253729007dd8667c65ad151040df71344aeb90c8120bc

test:
  secret_key_base: 2b3d087745004ccbc65d2018d6287cb507c1e6e5339ba1ac8e7e19a470dbd0f944b268860320d43d796e18a4f33d391d8a1fa15fa8bf30d70124cf2e6af2fc5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
