# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

MuwashafatUser.delete_all
Muwashafat.delete_all
Muwashafat.create([
  {name: "Tidak berhubungan dengan jin", level: 0, category: 0},
  {name: "Tidak meminta tolong kepada orang yang berlindung kepada jin", level: 0, category: 0},
  {name: "Tidak meramal nasib dengan melihat telapak tangan", level: 0, category: 0},
  {name: "Tidak menghadiri majelis dukun dan peramal", level: 0, category: 0},
  {name: "Tidak meminta berkah dengan mengusap-usap kuburan", level: 0, category: 0},
  {name: "Tidak meminta tolong kepada orang yang telah dikubur (mati)", level: 0, category: 0},
  {name: "Tidak bersumpah dengan selain Allah swt", level: 0, category: 0},
  {name: "Tidak tasya'um (merasa sial karena melihat atau mendengar sesuatu)", level: 0, category: 0},
  {name: "Mengikhlaskan amal untuk Allah swt", level: 0, category: 0},
  {name: "Mengimani rukun iman", level: 0, category: 0},
  {name: "Beriman kepada nikmat dan siksa kubur", level: 0, category: 0},
  {name: "Mensyukuri nikmat Allah swt saat mendapatkan nikmat", level: 0, category: 0},
  {name: "Menjadikan setan sebagai musuh", level: 0, category: 0},
  {name: "Tidak mengikuti langkah-langkah setan", level: 0, category: 0},
  {name: "Menerima dan tunduk secara penuh kepada Allah swt dan tidak bertahkim selain yang diturunkan-Nya", level: 0, category: 0},
  {name: "Ihsan dalam Thaharah", level: 0, category: 1},
  {name: "Ihsan dalam shalat", level: 0, category: 1},
  {name: "Membayar zakat", level: 0, category: 1},
  {name: "Berpuasa fardhu", level: 0, category: 1},
  {name: "Niat melaksanakan haji", level: 0, category: 1},
  {name: "Komitmen dengan adab tilawah", level: 0, category: 1},
  {name: "Menjauhi dosa besar", level: 0, category: 1},
  {name: "Memenuhi nadzar", level: 0, category: 1},
  {name: "Menyebar luaskan salam", level: 0, category: 1},
  {name: "Menahan anggota tubuh dari segala yang haram", level: 0, category: 1},
  {name: "Tidak sungkan adzan", level: 0, category: 1},
  {name: "Bersemangat untuk shalat berjamaah", level: 0, category: 1},
  {name: "Qiyamul-Lain minimal sekali sepekan", level: 0, category: 1},
  {name: "Berpuasa sunnah minimal sehari dalam sebulan", level: 0, category: 1},
  {name: "Khusyu dalam membaca Al-Quran", level: 0, category: 1},
  {name: "Hafal satu juz Al-Quran", level: 0, category: 1},
  {name: "Komitmen dengan wirid tilawah harian", level: 0, category: 1},
  {name: "Berdoa pada waktu-waktu utama", level: 0, category: 1},
  {name: "Menutup hari-harinya dengan bertobat dan beristighfar", level: 0, category: 1},
  {name: "Berniat pada setiap melakukan perbuatan", level: 0, category: 1},
  {name: "Merutinkan dzikir pagi hari", level: 0, category: 1},
  {name: "Merutinkan dzikir sore hari", level: 0, category: 1},
  {name: "Dzikir kepada Allah swt dalam setiap keadaan", level: 0, category: 1},
  {name: "Beri'tikaf pada bulan Ramadhan, jika mungkin", level: 0, category: 1},
  {name: "Mempergunakan siwak", level: 0, category: 1},
  {name: "Senantiasa menjaga kondisi Thaharah, jika mungkin", level: 0, category: 1},
  {name: "Tidak takabur", level: 0, category: 2},
  {name: "Tidak Imma'ah (asal ikut, tidak punya prinsip)", level: 0, category: 2},
  {name: "Tidak dusta", level: 0, category: 2},
  {name: "Tidak mencaci maki", level: 0, category: 2},
  {name: "Tidak mengadu domba", level: 0, category: 2},
  {name: "Tidak ghibah", level: 0, category: 2},
  {name: "Tidak menjadikan orang buruk sebagai teman/sahabat", level: 0, category: 2},
  {name: "Memenuhi janji", level: 0, category: 2},
  {name: "Birrul walidain", level: 0, category: 2},
  {name: "Memiliki ghirah (rasa cemburu) pada keluarganya", level: 0, category: 2},
  {name: "Memiliki ghirah (rasa cemburu) pada agamanya", level: 0, category: 2},
  {name: "Tidak memotong pembicaraan orang lain", level: 0, category: 2},
  {name: "Tidak mencibir dengan isyarat apapun", level: 0, category: 2},
  {name: "Tidak menghina dan meremehkan orang lain", level: 0, category: 2},
  {name: "Menyayangi yang kecil", level: 0, category: 2},
  {name: "Menghormati yang besar", level: 0, category: 2},
  {name: "Menundukkan pandangan", level: 0, category: 2},
  {name: "Menyimpan rahasia", level: 0, category: 2},
  {name: "Menutupi dosa orang lain", level: 0, category: 2},
  {name: "Menjauhi sumber penghasil haram", level: 0, category: 3},
  {name: "Menjauhi riba", level: 0, category: 3},
  {name: "Menjauhi judi dengan segala macamnya", level: 0, category: 3},
  {name: "Menjauhi tindak penipuan", level: 0, category: 3},
  {name: "Membayar zakat", level: 0, category: 3},
  {name: "Tidak menunda dalam melaksanakan hak orang lain", level: 0, category: 3},
  {name: "Menabung, meskipun sedikit", level: 0, category: 3},
  {name: "Menjaga fasilitas umum", level: 0, category: 3},
  {name: "Menjaga fasilitas khusus", level: 0, category: 3},
  {name: "Baik dalam membaca dan menulis", level: 0, category: 4},
  {name: "Memperhatikan hukum-hukum tilawah", level: 0, category: 4},
  {name: "Mengkaji marhalah Makkiyah dan menguasai karakteristiknya", level: 0, category: 4},
  {name: "Mengenal 10 sahabat yang dijamin masuk surga", level: 0, category: 4},
  {name: "Mengetahui hukum thaharah", level: 0, category: 4},
  {name: "Mengetahui hukum shalat", level: 0, category: 4},
  {name: "Mengetahui hukum puasa", level: 0, category: 4},
  {name: "Menyadari adanya peperangan Zionisme terhadap Islam", level: 0, category: 4},
  {name: "Mengetahui ghazwul fikri", level: 0, category: 4},
  {name: "Mengetahui organisasi-organisasi terselubung", level: 0, category: 4},
  {name: "Mengetahui bahaya pembatasan kelahiran", level: 0, category: 4},
  {name: "Berpartisipasi dalam kerja-kerja jama'i", level: 0, category: 4},
  {name: "Tidak menerima suara-suara miring tentang kita", level: 0, category: 4},
  {name: "Membaca satu juz tafsir Al-Quran (juz 30)", level: 0, category: 4},
  {name: "Menghafalkan separuh Arba'in (1-20)", level: 0, category: 4},
  {name: "Menghafalkan 20 hadits pilihan dari Riyadhus-Shalihin", level: 0, category: 4},
  {name: "Membaca sesuatu yang di luar spesialisasinya 4 jam setiap pekan", level: 0, category: 4},
  {name: "Memperluas wawasan diri dengan sarana-sarana baru", level: 0, category: 4},
  {name: "Menjadi pendengar yang baik", level: 0, category: 4},
  {name: "Mengemukakan pendapatnya", level: 0, category: 4},
  {name: "Bersih badan", level: 0, category: 5},
  {name: "Bersih pakaian", level: 0, category: 5},
  {name: "Bersih tempat tinggal", level: 0, category: 5},
  {name: "Komitmen dengan olah raga 2 jam setiap pekan", level: 0, category: 5},
  {name: "Bangun sebelum fajar", level: 0, category: 5},
  {name: "Memperhatikan tata cara baca yang sehat", level: 0, category: 5},
  {name: "Mencabut diri dari merokok", level: 0, category: 5},
  {name: "Komitmen dengan adab makan dan minum sesuai dengan sunnah", level: 0, category: 5},
  {name: "Tidak berlebihan dalam begadang", level: 0, category: 5},
  {name: "Menghindari tempat-tempat kotor dan polusi", level: 0, category: 5},
  {name: "Menghindari tempat-tempat bencana (bila masih di luar area)", level: 0, category: 5},
  {name: "Menjauhi segala yang haram", level: 0, category: 6},
  {name: "Menjauhi tempat-tempat maksiat", level: 0, category: 6},
  {name: "Menjauhi tempat-tempat bermain yang haram", level: 0, category: 6},
  {name: "Tidak menjalin hubungan dengan lembaga-lembaga yang menentang Islam", level: 0, category: 7},
  {name: "Memperbaiki penampilannya", level: 0, category: 7},
  {name: "Bangun pagi", level: 0, category: 8},
  {name: "Menghabiskan waktu untuk belajar", level: 0, category: 8},
  {name: "Melaksanakan hak kedua orang tua", level: 0, category: 9},
  {name: "Membantu yang membutuhkan", level: 0, category: 9},
  {name: "Memberi petunjuk orang tersesat", level: 0, category: 9},
  {name: "Ikut berpartisipasi dalam kegembiraan", level: 0, category: 9},
  {name: "Menikah dengan pasangan yang sesuai", level: 0, category: 9},

  {name: "Tidak mengkafirkan sesama muslim", level: 1, category: 0},
  {name: "Tidak mendahulukan makhluk atas Khalik", level: 1, category: 0},
  {name: "Mengingkari orang-orang yang memperolok-olokkan ayat-ayat Allah SWT dan tidak bergabung dengan majelis mereka", level: 1, category: 0},
  {name: "Mengesakan Allah SWT dalah Rubbubiyah dan Uluhiyah", level: 1, category: 0},
  {name: "Tidak menyekutukan Allah SWT, tidak dalam Asma'-Nya, sifat-Nya, dan Af'al-Nya", level: 1, category: 0},
  {name: "Tidak meminta berkah dengan mengusap-usap kuburan", level: 1, category: 0},
  {name: "Mempelajari madzhab-madzhab Islam yang berkaitan dengan Asma dan Sifat dan mengikuti madzhab salaf", level: 1, category: 0},
  {name: "Mengetahui batasan ber-wala' dan ber-bara'", level: 1, category: 0},
  {name: "Bersemangat untuk berteman dengan orang-orang shalih dari sisi-sisi  kedekatan dan peneladanan", level: 1, category: 0},
  {name: "Meyakini terhapusnya dosa dengan taubat Nashuha", level: 1, category: 0},
  {name: "Memprediksikan datangnya kematian kapan saja", level: 1, category: 0},
  {name: "Meyakini bahwa masa depan ada di tangan Islam", level: 1, category: 0},
  {name: "Berusaha meraih rasa manisnya iman", level: 1, category: 0},
  {name: "Berusaha meraih rasa manisnya ibadah", level: 1, category: 0},
  {name: "Merasakan adanya para malaikat mulia yang mencatat amalnya", level: 1, category: 0},
  {name: "Merasakan adanya istighfar para malaikat dan do'a mereka", level: 1, category: 0},

  {name: "Melakukan Qiyamulail minimal satu kali dalam satu pekan", level: 1, category: 1},
  {name: "Bersedekah", level: 1, category: 1},
  {name: "Berpuasa sunnah minimal dua hari dalam satu bulan", level: 1, category: 1},
  {name: "Haji jika mampu", level: 1, category: 1},
  {name: "Banyak bertobat", level: 1, category: 1},
  {name: "Memerintahkanyang ma'ruf", level: 1, category: 1},
  {name: "Mencegah yang munkar", level: 1, category: 1},
  {name: "Ziarah kubur untuk mengambil ibrah", level: 1, category: 1},
  {name: "Merutinkan ibadah-ibadah sunnah Rawatib", level: 1, category: 1},
  {name: "Khusyu dalam shalat", level: 1, category: 1},
  {name: "Khusyu saat membaca Al-Quran", level: 1, category: 1},
  {name: "Sekali khatam Al-Quran setiap dua bulan", level: 1, category: 1},
  {name: "Selalu memperbaharui niat dan meluruskannya", level: 1, category: 1},
  {name: "Menjaga tubuh (dari dosa)", level: 1, category: 1},
  {name: "Banyak dzikir kepada Allah SWT disertai hafalan terhadap yang mudah-mudah", level: 1, category: 1},
  {name: "Banyak berdoa dengan memperhatikan syarat-syarat dan tata kramanya", level: 1, category: 1},
  {name: "Senantiasa bertafakkur", level: 1, category: 1},
  {name: "Beri'tikaf satu malam setiap bulannya", level: 1, category: 1},

  {name: "Tidak inad (membangkang)", level: 1, category: 2},
  {name: "Tidak banyak mengobrol", level: 1, category: 2},
  {name: "Sedikit bercanda", level: 1, category: 2},
  {name: "Tidak berbisik dengan sesuatu yang bathil", level: 1, category: 2},
  {name: "Tidak hiqd (menyimpan kemarahan)", level: 1, category: 2},
  {name: "Tidak hasad", level: 1, category: 2},
  {name: "Memiliki rasa malu berbuat kesalahan", level: 1, category: 2},
  {name: "Menjalin hubungan baik dengan tetangga", level: 1, category: 2},
  {name: "Tawadhu tanpa merendahkan diri", level: 1, category: 2},
  {name: "Pemberani", level: 1, category: 2},
  {name: "Menjenguk orang sakit", level: 1, category: 2},
  {name: "Komitmen dengan adab meminta izin", level: 1, category: 2},
  {name: "Mensyukuri orang yang berbuat baik kepadanya", level: 1, category: 2},
  {name: "Menyambung silaturahim (shilatur-rahim)", level: 1, category: 2},
  {name: "Komitmen dengan tata krama sebagai pendengar", level: 1, category: 2},
  {name: "Komitmen dengan adab berbicara", level: 1, category: 2},
  {name: "Memuliakan tamu", level: 1, category: 2},
  {name: "Menjawab salam", level: 1, category: 2},
  {name: "Menebar senyum di depan orang lain", level: 1, category: 2},
  {name: "Berhati lembut", level: 1, category: 2},
  {name: "Merendahkan suara", level: 1, category: 2},

  {name: "Bekerja dan berpenghasilan", level: 1, category: 3},
  {name: "Berusaha memiliki spesialisasi", level: 1, category: 3},
  {name: "Sedam dalam nafkah", level: 1, category: 3},
  {name: "Mengutamakan produk-produk Islam", level: 1, category: 3},
  {name: "Menjaga kepemilikian khusus", level: 1, category: 3},
  {name: "Tidak berambisi menjadi pegawai negeri", level: 1, category: 3},
  {name: "Mengutamakan spesialisasi langka yang penting dan dinamis", level: 1, category: 3},
  {name: "Hartanya tidak pergi ke pihak non muslim", level: 1, category: 3},
  {name: "Berusaha untuk memperbaika kualitas produk dengan harga sesuai", level: 1, category: 3},

  {name: "Mengaitkan antara Al-Quran dengan realita", level: 1, category: 4},
  {name: "Mengkaji marhalah madaniyah dan menguasai karakteristiknya", level: 1, category: 4},
  {name: "Mengenal sirah 20 sahabat yang syahid", level: 1, category: 4},
  {name: "Mengetahui hukum zakat", level: 1, category: 4},
  {name: "Mengetahui fiqih haji", level: 1, category: 4},
  {name: "Mengetahui sisi-sisi syumuliyatul Islam", level: 1, category: 4},
  {name: "Mengetahui problematika kaum muslimin internal dan eksternal", level: 1, category: 4},
  {name: "Mengetahui apa kerugian dunia akibat kemunduran kaum muslimin", level: 1, category: 4},
  {name: "Mengetahui urgensi Khilafah dan kesatuan kaum muslimin", level: 1, category: 4},
  {name: "Mengetahui dan mengulas 'tiga risalah', yaitu: Da'watuna, Ila Ayyi Sya'in Nad'un dan Ilasy-Syabab", level: 1, category: 4},
  {name: "Mengetahui dan mengulas 'Risalah Aqaid'", level: 1, category: 4},
  {name: "Memahami amal jama'i dan taat", level: 1, category: 4},
  {name: "Membantah suara-suara miring yang dilontarkan kepada kita", level: 1, category: 4},
  {name: "Mengetahui bagaimana proses berdirinya negara Israel", level: 1, category: 4},
  {name: "Membaca tafsir dua juz Al-Quran (28-29)", level: 1, category: 4},
  {name: "Mengetahui arah-arah pemikiran Islam kontemporer", level: 1, category: 4},
  {name: "Memiliki kemampuan mengulas apa yang ia baca", level: 1, category: 4},
  {name: "Hafal dan bertajwid tiga juz Al-Quran (28-30)", level: 1, category: 4},
  {name: "Menghafalseluruh hadits 'Arbain Nawawi' (20 + 20)", level: 1, category: 4},
  {name: "Menghafal 50 hadits 'Riyadhus-Shalihin' (20 + 30)", level: 1, category: 4},
  {name: "Membaca tujuh jam setiap pekan di luar spesialisasinya", level: 1, category: 4},
  {name: "Menghadiri konferensi dan seminar kita", level: 1, category: 4},
  {name: "Mengenali hal-hal baru dari problematika kekinian", level: 1, category: 4},
  {name: "Menyebarluaskan apa saja yang diterbitkan oleh koran dan terbitan kita", level: 1, category: 4},
  {name: "Berpartisipasi dalam melontarkan dan memecahkan masalah", level: 1, category: 4},

  {name: "Membersihkan peralatan makan dam minumnya", level: 1, category: 5},
  {name: "Mampu mempersiapkan makanan", level: 1, category: 5},
  {name: "Mengikuti petunjuk-petunjuk kesehatan dalam tidur dan bangun tidur semampunya, seperti:", level: 1, category: 5},
  {name: "Mengobati diri sendiri", level: 1, category: 5},
  {name: "Tidak mempergunakan obat tanpa meminta petunjuk", level: 1, category: 5},
  {name: "Menjauhi makanan-makanan yang diawetkan dan mempergunakan minuman-minuman alami", level: 1, category: 5},
  {name: "Mengatur waktu-waktu makan", level: 1, category: 5},
  {name: "Tidak berlebihan mengkonsumsi lemak", level: 1, category: 5},
  {name: "Tidak berlebihan mengkonsumsi garam", level: 1, category: 5},
  {name: "Tidak berlebihan mengkonsumsi gula", level: 1, category: 5},
  {name: "Memilih produsen-produsen makanan", level: 1, category: 5},
  {name: "Tidur 6-8 jam dan bangun sebelum fajar", level: 1, category: 5},
  {name: "Berlatih 10-15 menit setia hari", level: 1, category: 5},
  {name: "Berjalan 2-3 jam setiap pekan", level: 1, category: 5},

  {name: "Selalu menyertakan niat jihad", level: 1, category: 6},
  {name: "Menjadikan dirinya bersama orang baik", level: 1, category: 6},
  {name: "Menyumbangkan sebagian hartanya untuk amal islami", level: 1, category: 6},
  {name: "Sabar atas bencana", level: 1, category: 6},
  {name: "Menyesuaikan perbuatan dengan ucapan", level: 1, category: 6},
  {name: "Menerima dan memikul beban dakwah", level: 1, category: 6},
  {name: "Memerangi dorongan-dorongan nafsu", level: 1, category: 6},
  {name: "Tidak berlebihan mengkonsumsi yang mubah", level: 1, category: 6},
  {name: "Memakan apa yang disuguhkan dengan penuh keridhaan", level: 1, category: 6},

  {name: "Shalat menjadi baromter manajemen waktunya", level: 1, category: 7},
  {name: "Teratur di dalam rumah dan kerjanya", level: 1, category: 7},
  {name: "Menertibkan ide-ide dan pikiran-pikirannya", level: 1, category: 7},
  {name: "Bersemangat memenuhi janji-janji kerja", level: 1, category: 7},
  {name: "Memberitahukan gurunya problematika-problematika yang muncul", level: 1, category: 7},

  {name: "Nenjaga janji-janji umum dan khusus", level: 1, category: 8},
  {name: "Mengisi waktunya dengan hal-hal yang berfaedah dan bermanfaat", level: 1, category: 8},
  {name: "Memperhatikan adab Islam dalam berkunjung dan mempersingkat pemenuhan hajatnya", level: 1, category: 8},

  {name: "Komitmen dengan adab Islam di rumah", level: 1, category: 9},
  {name: "Melaksanakan hak-hak pasangannya (suami atau istri)", level: 1, category: 9},
  {name: "Melaksanakan hak-hak anak", level: 1, category: 9},
  {name: "Memberi hadiah kepada tetangga", level: 1, category: 9},
  {name: "Membantu yang membutuhkan", level: 1, category: 9},
  {name: "Menolong yang terzhalimi", level: 1, category: 9},
  {name: "Bersemangat endakwahi istrinya, anak-anaknya, dan kerabatnya", level: 1, category: 9},
  {name: "Mendoakan yang bersin", level: 1, category: 9},
  {name: "Membantu istrinya", level: 1, category: 9},
  {name: "Memberikan pelayanan umum karena Allah SWT", level: 1, category: 9},
  {name: "Memberikan sesuatu dari yang dimiliki", level: 1, category: 9},
  {name: "Mendekati orang lain", level: 1, category: 9},
  {name: "Mendorong orang lain berbuat baik", level: 1, category: 9},
  {name: "Membantu yang kesulitan", level: 1, category: 9},
  {name: "Membantu yang terkena musibah", level: 1, category: 9},
  {name: "Berusaha memenuhi hajat orang lain", level: 1, category: 9},
  {name: "Memberi makan orang lain", level: 1, category: 9},
])

YaumiyahReport.delete_all
Yaumiyah.delete_all
Yaumiyah.create([
    {name: "Tahajud", description: "Isi dengan 1 jika iya, dan 0 jika tidak"},
    {name: "Shalat Berjamaah", description: "Isi dengan jumlah shalat wajib berjamaah, maksimal 5"},
    {name: "Dhuha", description: "Isi dengan 1 jika iya, dan 0 jika tidak"},
    {name: "Tilawah", description: "Isi dengan jumlah juz yang dibaca dalam satu hari"},
    {name: "Sedekah", description: "Isi dengan 1 jika iya, dan 0 jika tidak"}
  ])

